arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: L10n
output-dir: lib/generated/l10n
synthetic-package: false
untranslated-messages-file: lib/l10n/untranslated.txt