name: Flutter Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  FLUTTER_VERSION: "3.24.5"
  JAVA_VERSION: "17"

permissions:
  contents: write
  actions: read

jobs:
  releaseAndroid:
    name: Release Android
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "gradle"
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK and App Bundle
        run: |
          flutter build apk --release --split-per-abi
          flutter build appbundle --release
      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-${{ github.run_number }}
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 3
          compression-level: 9
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/app-release.aab
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releaseLinux:
    name: Release Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: Cache Linux dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-
            
      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Build Linux
        run: flutter build linux --release
      - name: Package Linux app
        run: |
          cd build/linux/x64/release/bundle
          tar -czf skylink-linux-x64.tar.gz *
          
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-${{ github.run_number }}
          path: build/linux/x64/release/bundle/skylink-linux-x64.tar.gz
          retention-days: 3
          compression-level: 9
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x64/release/bundle/skylink-linux-x64.tar.gz
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releaseWindows:
    name: Release Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\Pub\Cache
            ${{ runner.tool_cache }}\flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Windows
        run: flutter build windows --release
      - name: Package Windows app
        run: |
          cd build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath skylink-windows-x64.zip -CompressionLevel Optimal
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-${{ github.run_number }}
          path: build/windows/x64/runner/Release/skylink-windows-x64.zip
          retention-days: 3
          compression-level: 9
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/windows/x64/runner/Release/skylink-windows-x64.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releaseMacOS:
    name: Release macOS
    runs-on: macos-latest
    timeout-minutes: 35
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build macOS
        run: flutter build macos --release
      - name: Package macOS app
        run: |
          cd build/macos/Build/Products/Release
          zip -r skylink-macos-universal.zip skylink.app
          
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-${{ github.run_number }}
          path: build/macos/Build/Products/Release/skylink-macos-universal.zip
          retention-days: 3
          compression-level: 9
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/macos/Build/Products/Release/skylink-macos-universal.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releaseWeb:
    name: Release Web
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Web
        run: flutter build web --release --web-renderer canvaskit
      - name: Package Web app
        run: |
          cd build/web
          tar -czf skylink-web.tar.gz *
          
      - name: Upload Web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-release-${{ github.run_number }}
          path: build/web/skylink-web.tar.gz
          retention-days: 3
          compression-level: 9
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/web/skylink-web.tar.gz
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}